services:
  - type: web
    name: skor-bola
    runtime: node
    plan: free
    buildCommand: ""
    startCommand: node server/dist/index.mjs
    envVars:
      - key: STATIC_DIR
        value: ./web
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
